In [3]:
import numpy as np
from linearalgebrafns import *

In [4]:
testmatrix=np.array([[2,3,1],[4,7,3],[6,18,5]])

In [5]:
def LU(matrix):
    numrows=matrix.shape[0]
    U=matrix
    L=np.identity(numrows)
    for i in range(numrows):
        Li=np.identity(numrows)
        Li[i,i]=Li[i,i]/U[i,i]
        L[i,i]=L[i,i]*U[i,i]
        for j in range(i+1, numrows):
            Li[j,i]=-U[j,i]/U[i,i]
            L[j,i]=U[j,i]
        U=multiplymatrices(Li,U)
    return L,U

In [6]:
testmatrix=np.array([[2,3,1],[4,7,3],[6,18,3]])
L,U=LU(testmatrix)
print(L)
print(U)

[[ 2.  0.  0.]
 [ 4.  1.  0.]
 [ 6.  9. -9.]]
[[1.  1.5 0.5]
 [0.  1.  1. ]
 [0.  0.  1. ]]


In [7]:
multiplymatrices(L,U)

array([[ 2.,  3.,  1.],
       [ 4.,  7.,  3.],
       [ 6., 18.,  3.]])

In [44]:
def FS(matrix, vector): #only apply to lower triangular matrix
    numrows=matrix.shape[0]
    solns=np.zeros(numrows)
    for i in np.arange(numrows): 
        rightsum=0
        for j in range(0,i):
            rightsum+=matrix[i,j]*solns[j]
        solns[i]=(vector[i]-rightsum)/matrix[i,i]
    return solns

In [36]:
testvector=np.array([1,2,6])
y=FS(L,testvector)

0
1 0
0
2.0
2 0
0
2 1
3.0
3.0


In [38]:
y

array([ 0.5       ,  0.        , -0.33333333])

In [40]:
x=BS(U,y)

In [42]:
x

array([ 0.16666667,  0.33333333, -0.33333333])

In [47]:
def solve_LU(L,U,v):
    y=FS(L,v)
    x=BS(U,y)
    return x

In [49]:
solve_LU(L,U,testvector)

array([ 0.16666667,  0.33333333, -0.33333333])

In [51]:
solve_LU(L,U,np.array([1,2,3]))

array([ 0.5,  0. , -0. ])

In [53]:
solve_LU(L,U,np.array([7,2,3]))

array([ 11.5,  -2. , -10. ])